name: Terraform Verification CI
on:
  push: #run this workflow whenever a branch was pushed

jobs:
  TerraformCI:
    name: Run terraform ci
    runs-on: 'windows-latest'
    steps:  
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - name: terraform fmt
        run: |
          terraform fmt -recursive -no-color

      - name: terraform validate 
        run: |
          terraform validate -no-color
